// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_new from "./routes/api/new.tsx";
import * as $api_yotei from "./routes/api/yotei.tsx";
import * as $events_id_ from "./routes/events/[id].tsx";
import * as $events_new from "./routes/events/new.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $new from "./routes/new.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Yotei from "./islands/Yotei.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/new.tsx": $api_new,
    "./routes/api/yotei.tsx": $api_yotei,
    "./routes/events/[id].tsx": $events_id_,
    "./routes/events/new.tsx": $events_new,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/new.tsx": $new,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Yotei.tsx": $Yotei,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
